language: node_js
node_js:
- '14'
before_install:
- npm install -g @angular/cli
install: npm install
branches:
  only:
  - master
deploy:
  provider: heroku
  app: steams-store
  api_key:
    secure: cJPPXQlsQpnZVgWJVbN3snvRRwcGBFHe21AsMzCMFBpKSsdrX85gKrJ9O3ehcnfXhW3Q0HnuPf5OJt2s4lczWhgCLLUgizfZrvsXDlbBgEUITUDKbdLJAfYPxt7g2nMfsWrK2e9lm1XhiJb1lIsBbbgiGf2PpMaQ3WeTBkbRU9RuILLYeGBMUjmzpGC/owMLN6/n/YTSawP5Bj9+r2tfbb8v5SBnbm1ZHCgDd5wU1YRLQkILkajEpO9H25ELcRwhoNz5fQswZHKzWuG/qdYa5beK+9xIke+ASI/jAGoAo9ZydJDW7pA//M4cO4jFACMMU/5SK47jKVVtPBdLqGvkj9rOEQhTnVYKlbGHIMamGEI4oL3QY3sXgPTNXIQWRQ2jmUQ6CK10Q8Q1953oW9dnY5U44nD+PAf85vs9g4iPue6dDpeSHYgS9CcPMgB1oY8sUYdguK+OGaknZLm74vTRmgo6J2YIyu3znViSurV4WVeHQN4zG04dYRmOvzRvBXLbxCFn2pjLs9okxzH5deY9H7l5NbH5IC+L0QRzzufkAvyAvBm/8cpZ5tPupWSyAWcwEOox6+vvGTK71r+0mN9awg6WIafgvER/QbHNUm3of/ZHIFcQEV9OmfBP+mQQBpKlExSRiqzAfiQqPo7fA9Bm/wAiBNH7epgoySkPL6qzs2Y=
